spring:
  application:
    name: retry-producer-service

server:
  port: ${SERVER_PORT:9001}




#management:
#  endpoints:
#    web:
#      exposure:
#        include=*:
#      cors:
#        allowed-methods=GET

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always

# To expose only selected endpoints
#management.endpoints.jmx.exposure.include=health,info,env,beans

#  management.endpoints.enabled-by-default=false
#  management.endpoint.info.enabled=true
#  management.endpoint.health.enabled=true
#  management.endpoint.loggers.enabled=true

#https://howtodoinjava.com/spring-boot/actuator-endpoints-example/:

  management:
    endpoints:
      enabled-by-default: true
      web:
        exposure:
          include: health,info,metrics,env










  # or to expose all
#  management.endpoints.web.exposure.include=*

logging:
  file:
    name: logs/app.log