# Before working with this project please be ready with docker mySQL container.

spring:
  profiles:
    active: ${SPRING_PROFILE:h2}
  datasource: # MYSQL Database Configurations
    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: kamal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # or create, create-drop, none, validate
    show-sql: true # set to false in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Adjust based on your MySQL version
  application:
    name: retry-producer-service

server:
  port: ${SERVER_PORT:9001}




#management:
#  endpoints:
#    web:
#      exposure:
#        include=*:
#      cors:
#        allowed-methods=GET

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always

# To expose only selected endpoints
#management.endpoints.jmx.exposure.include=health,info,env,beans

#  management.endpoints.enabled-by-default=false
#  management.endpoint.info.enabled=true
#  management.endpoint.health.enabled=true
#  management.endpoint.loggers.enabled=true

#https://howtodoinjava.com/spring-boot/actuator-endpoints-example/:

  management:
    endpoints:
      enabled-by-default: true
      web:
        exposure:
          include: health,info,metrics,env










  # or to expose all
#  management.endpoints.web.exposure.include=*

logging:
  file:
    name: logs/app.log
