eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: api-gate-way-scg
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://FIRST-SERVICE/
          predicates:
            - Path=/fs/**
        - id: second-service
          uri: lb://SECOND-SERVICE/
          predicates:
            - Path=/ss/**
server:
  port: 9000



